import { useEffect, useState } from "react";
import { getCandidates, getJob, getJobs, getMatch } from "../services/api.js";

function Matching() {
    const [candidates, setCandidates] = useState([]); const [jobs, setJobs] = useState([]); const [candidateId, setCandidateId] = useState(""); const [jobId, setJobId] = useState(""); const [result, setResult] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
    useEffect(() => { Promise.all([getCandidates(), getJobs()]).then(([candidateData, jobData]) => { setCandidates(candidateData); setJobs(jobData); setCandidateId(String(candidateData[0]?.id || "")); setJobId(String(jobData[0]?.id || "")); }).catch(() => setError("Unable to load matching data.")); }, []);
    async function compare(event) { event.preventDefault(); setLoading(true); setError(""); try { setResult(await getMatch(candidateId, jobId)); } catch (err) { setError(err.message); } finally { setLoading(false); } }
    return <section className="workspace-page"><div className="workspace-heading"><div><p className="eyebrow">Decision support</p><h1>AI matching</h1><p className="subheading">Compare evidence transparently. Recruiters make the final decision.</p></div><span className="demo-chip">Human review required</span></div><form className="surface-card match-form" onSubmit={compare}><label>Candidate<select value={candidateId} onChange={(event) => setCandidateId(event.target.value)}>{candidates.map((item) => <option value={item.id} key={item.id}>{item.name} · {item.role}</option>)}</select></label><label>Job<select value={jobId} onChange={(event) => setJobId(event.target.value)}>{jobs.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><button className="btn btn-primary" disabled={loading || !candidateId || !jobId}>{loading ? "Comparing..." : "Compare profile"}</button></form>{error && <p className="error-state">{error}</p>}{result && <article className="surface-card match-result"><div className="match-score"><strong>{result.score}%</strong><span>overall match</span></div><div><p className="eyebrow">{result.candidate.name} · {result.job.title}</p><h2>Evidence, not an automatic verdict.</h2><p>{result.calculation}</p></div><div className="match-columns"><div><b>Matching skills</b><div className="skill-list">{result.matching_skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div><div><b>Missing skills</b><div className="skill-list missing">{(result.missing_skills.length ? result.missing_skills : ["None detected"]).map((skill) => <span key={skill}>{skill}</span>)}</div></div></div><p className="field-hint">Experience: {result.experience.candidate} · requirement: {result.experience.required} · {result.experience.meets_requirement ? "meets requirement" : "below stated requirement"}</p></article>}</section>;
}
export default Matching;
